### ISSUE TITLE
querying metadata is not returning all needed metadata

### ISSUE THREAD

**Issue by juliasilge** [ropenscilabs/gutenbergr#5]
When I use `gutenberg_metadata` or `gutenberg_works`, the query is not returning all of the metadata, including, most importantly, the Gutenberg ID, or quite a number of other fields listed in the docs. For example, if I do this:
```
library(gutenberg)
library(stringr)
some_metadata <- gutenberg_works(author == "Shakespeare, William", !str_detect(title, "Works"))
```
I get a data frame that is 66 x 2 that includes only columns for title and `gutenberg_author_id` (all 65 in this case) but nothing else, no `gutenberg_id` which is what I would need to go on to do `gutenberg_download`. Have you seen this? Any ideas?

Here is my session info:
```
R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.4 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] stringr_1.0.0        gutenbergr_0.1.1     tidytext_0.1.0.9000  Matrix_1.2-6         janeaustenr_0.1.0    topicmodels_0.2-4   
 [7] dplyr_0.4.3.9001     tm_0.6-2             NLP_0.1-9            testthat_1.0.2       devtools_1.11.1.9000
```

**Comment by dgrtwo** [comment]
I am able to reproduce this with `dplyr_0.4.3.9001` (not earlier). Investigating!

**Comment by juliasilge** [comment]
Aaaaaah, I just updated to the development version of dplyr for its new release, etc!
