### ISSUE TITLE
Using gutenbergr in vignettes -- HTTP error 403

### ISSUE THREAD

**Issue by juliasilge** [ropenscilabs/gutenbergr#6]
This package is so useful and put together well, but I do have a long-running, intermittent issue with it that I am not sure what to do about. When I use gutenbergr functions in a package vignette, building the package on Travis/AppVeyor fails sometimes because of a 403 error from Project Gutenberg, like so:
```
Determining mirror for Project Gutenberg from http://www.gutenberg.org/robot/harvest
Quitting from lines 37-46 (topic_modeling.Rmd) 
Error: processing vignette 'topic_modeling.Rmd' failed with diagnostics:
HTTP error 403.
Execution halted
```
This doesn't happen every time, and I have not been able to really predict when would be more likely to succeed vs. fail. If it does fail, generally it will fail again and again for the next several hours, up to a whole day. On the other hand, sometimes I can go many hours/commits with all successes.

I know Project Gutenberg is picky about automated traffic. Is there something I can do about this as a user or vignette writer? Any thoughts?

**Comment by juliasilge** [comment]
Gosh, when I merged https://github.com/juliasilge/tidytext/pull/15 this morning, I ran into this issue again. Is there anything I can do about this? Is there a way to get a vignette using gutenbergr to consistently build on Travis?

**Comment by dgrtwo** [comment]
I know, this is really annoying! Here's my proposal.

Let's have the results of the `gutenberg_download` code saved in an .rda file in `inst`. Then we'll set the vignette chunk to eval = FALSE, and have a second chunk, with echo = FALSE, that loads it in. Something like:

    load(system.file("inst", "books.rda", package = "tidytext"))

This is cheating a *bit* with reproducibility, but it will make it both look and behave correctly, and never need to query Project Gutenberg when building vignettes. If you agree I can make that change in tidytext right now.

**Comment by dgrtwo** [comment]
Sorry: specifically `inst/extdata`, not just `inst`

**Comment by juliasilge** [comment]
OK, I think this is a good workaround. I sure am glad that the vignette built on CRAN without problems when we submitted.

For the record, I have never had gutenbergr give me a error when I am using it interactively or building vignettes from my own computer, or using knitr for making a blog post or anything like that.

**Comment by dgrtwo** [comment]
I agree, it's pretty odd! Maybe some of the Travis or Appveyor servers have IP addresses that are blacklisted.

**Comment by dgrtwo** [comment]
This should do it!

**Comment by juliasilge** [comment]
I don't know if you're going to add anything to the gutenbergr docs about using it when building on Travis, but the vignettes have so far built perfectly 100% of the time on AppVeyor; it is only on Travis that they have intermittently had problems.

**Comment by dgrtwo** [comment]
Oh ok!

**Comment by juliasilge** [comment]
I realize now I said this wrong in the original post for this issue. :confused: Sorry about that!
