### ISSUE TITLE
Problem with use of gutenberg_download function

### ISSUE THREAD

**Issue by joelcourtheyn** [ropenscilabs/gutenbergr#8]
I'm receiving following error message when  trying to download.  Can someone give advice ?
> library(gutenbergr)
> wuthering_heights <- gutenberg_download(768)
Determining mirror for Project Gutenberg from http://www.gutenberg.org/robot/harvest
Using mirror http://www.gutenberg.lib.md.us
Warning messages:
1: In .f(.x[[i]], ...) :
  Could not download a book at http://www.gutenberg.lib.md.us/7/6/768/768.zip
2: Unknown column 'text' 
3: In is.na(text) : is.na() applied to non-(list or vector) of type 'NULL'

**Comment by crogger62** [comment]
Me too. I wonder if the host is down?

**Comment by frnz347** [comment]
I have a the same problem :(

**Comment by dgrtwo** [comment]
Unfortunately this Project Gutenberg mirror appears to be down today (e.g. [see here](http://www.gutenberg.lib.md.us/etext01/alpsn10.zip)).

The good news is that you can get around it by choosing another mirror from [this page](https://www.gutenberg.org/MIRRORS.ALL) and giving it as the `mirror` argument. For example, please try:

    wuthering_heights <- gutenberg_download(768, mirror = "http://mirrors.xmission.com/gutenberg/")

I'll try the original mirror again tomorrow, and if the problem continues I'll try contacting Project Gutenberg. (If that doesn't work I'll try to make an easier way to set backup mirrors in the software).

**Comment by frnz347** [comment]
@dgrtwo thanks, it worked for me

**Comment by joelcourtheyn** [comment]
@dgrtwo Thanks for your quick reply, it worked !
I was already guessing that there was something wrong with my computer connexion at the server part.
Congratulations to you and your colleague Julia Silge with your new book : Text Mining in R !
I discovered quite a lot of  new things to me s.a. the very interesting gutenbergr package,

**Comment by dgrtwo** [comment]
FYI, I've committed a change to dev (26f0639530ce24c6d895a5edb25fac2a783dca0c) that fixes this. Planning to submit to CRAN shortly.

I've emailed Project Gutenberg twice and they haven't replied.

**Comment by dgrtwo** [comment]
I haven't yet submitted to CRAN but Project Gutenberg was quite helpful and changed the default mirror on the site. This should now work (including in the CRAN version)!

**Comment by vs6f8** [comment]
This is still not working. I am getting the same error.

**Comment by crogger62** [comment]
Both of these worked for me:
wuthering_heights <- gutenberg_download(768, mirror = "http://mirrors.xmission.com/gutenberg/")
and
wuthering_heights <- gutenberg_download(768, mirror = "http://mirrors.xmission.com/gutenberg/")

What error are you getting?

**Comment by vs6f8** [comment]
Hi, I tried it again and am getting the same error, the error is as follows
![image](https://user-images.githubusercontent.com/13352250/55262107-c8aef200-523a-11e9-9e6c-e64b5dd8ae5f.png)

**Comment by crogger62** [comment]
What happens if you navigate to the URL in the red text: "http://mirrors.xmission.com/gutenberg//7/6/768/768.zip" ? You should end up downloading 768.zip which is text for wuthering heights. 

Your second warning "Unknown or uninitialised column: 'text'." seems to be a problem with getting the data into the data frame (tbl_df). One of the columns is called 'text' and it looks like there is a problem getting it there. 

I'd suggest making sure your packages are up to date. Make sure you're loading dplyr 
library(dplyr) 
too.

**Comment by lejarx** [comment]
Thought this would still be useful, the default aleph mirror doesn't work.

Available mirrors are at
https://www.gutenberg.org/MIRRORS.ALL

I'm using ''http://www.gutenberg.org/dirs/'', it works.
